CREATE TABLE "GCG_3138_AR_WEEKLY"(
 "BIRUNID" BIGINT,
 "CUSTOMER" VARCHAR(6),
 "INVOICE" VARCHAR(7),
 "INVOICE_DATE" DATE,
 "DUE_DATE" DATE,
 "CURR_WEEK" DOUBLE,
 "WEEK_1" DOUBLE,
 "WEEK_2" DOUBLE,
 "WEEK_3" DOUBLE,
 "WEEK_4" DOUBLE,
 "NAME_CUSTOMER" VARCHAR(30),
 "TERMS_CODE" VARCHAR(1),
 "PAST_DUE" DOUBLE);
